### PR TITLE
cursor and thickness bugfix

### PR DESCRIPTION
**Pull request by cantbesure1**
changes:

1. changed cursor to match mouse position more naturally
2. fixed a bug where the cursor could appear 1 row or column outside the grid
3. made thickness stop decreasing at zero, making negative thickness impossible

### CODE REVIEW

**Comment by cantbesure1** [comment]
found a rather large bug

**Comment by neauoire** [comment]
A large bug?!

**Comment by cantbesure1** [comment]
in my code, not yours. Fixed now, sorry for the delay. I'm glad I caught that though :P

**Comment by neauoire** [comment]
Oh wow, the cursor feels a lot better.

**Pull request merged**
